### ISSUE TITLE
where is the  image of cat in result.

### ISSUE THREAD

**Issue by panhu** [erikreppel/visualizing_cnns#1]
when  i run the code,can't see the image of cat ,.Just the ‘print‘  shows in output

**Comment by cmasch** [comment]
@panhu pls try to add `%matplotlib inline` to your notebook. Otherwise call `plt.show()` right after `plt.imshow(xxx)`

**Comment by erikreppel** [comment]
Yep! I should have thrown `%matplotlib inline` in the notebook
